### ISSUE TITLE
HvDropdown in combination with useContext() issue

### ISSUE THREAD

**Issue by pavvarpet** [lumada-design/hv-uikit-react#4202] opened 2024-06-14 07:53 UTC
### Discussed in https://github.com/lumada-design/hv-uikit-react/discussions/4199

<div type='discussions-op-text'>

<sup>Originally posted by **pavvarpet** June  7, 2024</sup>
Greetings, and thank you for your work.

Is it possible to use dropdown onChange method to set the value inside react state?

When we did something like:
```
  const onChange = (e: any) => {
    console.log(e);
    console.log("Implement this onChange");
    setVal(e.label);
    console.log(val + " is selected.");
  };
  const [val, setVal] = useState("");
  ```
  
In this case the dropdown component becomes broken for some reason... :/</div>

**Comment by MEsteves22** [comment] 2024-06-14 10:48
Hello @pavvarpet 👋

Yes, you can use the `onChange` handler in `HvDropdown`. How are you using `val` afterwards? Can you reproduce the problem in this [stackblitz](https://stackblitz.com/github/lumada-design/hv-uikit-react/tree/master/examples/uikit-vite-ts), please? It would be a lot easier for us to troubleshoot this 🙏

**Comment by pavvarpet** [comment] 2024-06-14 10:59
Nowhere actually except that onChange function.. most basic scenario

**Comment by MEsteves22** [comment] 2024-06-19 16:45
I see @pavvarpet. You should put your dropdown values inside a `useMemo` hook:

```
 const values = useMemo(
    () => [
      { label: 'value 1' },
      { label: 'value 2', selected: true },
      { label: 'value 3' },
      { label: 'value 4' },
    ],
    []
  );
```

**Comment by pavvarpet** [comment] 2024-06-20 02:21
Hello Marcia, thank you it definitely works better with useMemo hook, however is there an explanation why does it print the old value in console:
<img width="1374" alt="image" src="https://github.com/lumada-design/hv-uikit-react/assets/135119359/c0aba1f8-c19e-4d99-8707-f7ac2fca628c">
onChange function look like this:
`const onChange14745722 = (e: any) => {
    setVal(e.label);
    console.log(e.label + " is selected.");
    console.log("Implement this onChange14745722");
    console.log(val + " is selected.");
  };`

So the last console log prints out the old value even though the setter is called in the first line.

**Comment by MEsteves22** [comment] 2024-06-20 08:19
Hello @pavvarpet,
This is happening because `setVal` is an async function (all `useState` are async). Thus, if you do a `console.log` after using `setVal`, `val` is not yet updated and the old value is printed. 
If you need to do a `console.log`, do it outside the `onChange` function or use a `useEffect` to only print `val` when it changes:

```tsx
useEffect(()=>{
    console.log(val + " is selected.");
}, [val])
```

I'll close the issue since this was solved.

**Closed by MEsteves22** 2024-06-20 08:19 UTC
Labels: :mailbox_with_mail: waiting feedback
