### ISSUE TITLE
Vertical Navigation - Slider Mode - vertical scrollbar should not scroll to the top when selecting an option that is on the very bottom

### ISSUE THREAD

**Issue by paulaclemente** [lumada-design/hv-uikit-react#3324] opened 2023-05-12 15:13 UTC
### Latest version

- [X] I have tested the latest version

### No Hitachi confidential content

- [X] I'm not including any Hitachi confidential content

### Current behavior 😯

Having a long list of menu items, if we scroll down to select an option that is on the bottom (and does not have submenus), when that item is selected the scrollbar scrolls to the top and we do not see the item that was selected anymore.

https://github.com/lumada-design/hv-uikit-react/assets/412752/1ac02c52-b505-4aa9-b239-647f68fc07b9

### Expected behavior 🤔

Having a long list of menu items, if we scroll down to select an option that is on the bottom (and does not have submenus), when that item is selected we should continue to see the item selected. The scrollbar position should be kept.

**Comment by plagoa** [comment] 2023-05-19 09:57
@paulaclemente we were unable to reproduce the error. Can you provide more context and, if possible, reproduce it here:

https://stackblitz.com/github/lumada-design/hv-uikit-react/tree/master/examples/uikit-vite-ts

**Comment by francisco-guilherme** [comment] 2023-07-13 22:00
@paulaclemente any feedback on this?

**Comment by paulaclemente** [comment] 2023-07-14 15:37
Hi @plagoa and @francisco-guilherme.
We were not able to reproduce the original issue with the link you provided.

However, we keep seeing similar issues (related with scrolls) in our environment.
Eg: When we are on a page which corresponds to a menu entry that is listed on the very bottom of the list, when we open the menu the actual selected item is not visible (we need to scroll down to see it).

https://github.com/lumada-design/hv-uikit-react/assets/412752/6802ccf9-b7de-49e5-860b-ae6e1d270677

**Comment by zettca** [comment] 2023-08-04 14:13
I'm closing this as the original issue can't be reproduced.

Regarding the scrolling of the element, it's not clear when (or not) to scroll to the selected element.
And this can be added to the app by using something like [`scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).
Please open a new issue regarding the auto-scrolling if this suggestion doesn't fit your use-case, and we'll look into it

**Closed by zettca** 2023-08-04 14:13 UTC
