### ISSUE TITLE
Unable to render data after Build/ Unable to se the data in DOM || row is undefined

### ISSUE THREAD

**Issue by Srikant1290** [lumada-design/hv-uikit-react#4163] opened 2024-04-23 14:04 UTC
### Discussed in https://github.com/lumada-design/hv-uikit-react/discussions/4162

<div type='discussions-op-text'>

<sup>Originally posted by **Srikant1290** April 23, 2024</sup>
 <HvTableRow {...row.getRowProps()}>
        {row.cells.map((cell) => (
          <HvTableCell {...cell.getCellProps()}>
            {cell.render("Cell")}
          </HvTableCell>
        ))}
      </HvTableRow>
      
      I am not able to see the data in the dom itself after Build</div>

**Comment by zettca** [comment] 2024-04-23 15:46
Hey @Srikant1290 👋 

Please share more of the code. Are you calling `prepareRow(row)`? Is the table receiving the `data` correctly?

You can use our [Stackblitz template](https://stackblitz.com/github/lumada-design/hv-uikit-react/tree/master/examples/uikit-vite-ts) to create a repo path

**Comment by Srikant1290** [comment] 2024-04-23 16:10
here the cell value I am getting inside the page is Undefined after build, in local it is working Fine

**Comment by Srikant1290** [comment] 2024-04-23 16:10
import { css, keyframes } from '@emotion/css';
import {
  baseDropdownClasses,
  HvButton,
  HvFilterGroup,
  HvFilterGroupProps,
  HvFilterGroupValue,
  HvInput,
  HvPagination,
  HvTable,
  HvTableBody,
  HvTableCell,
  HvTableColumnConfig,
  HvTableContainer,
  HvTableHead,
  HvTableHeader,
  HvTableRow,
  HvTableSection,
  HvTypography,
  theme,
  useHvData,
  useHvFilters,
  useHvGlobalFilter,
  useHvSortBy,
  useHvPagination,
} from '@hitachivantara/uikit-react-core';
import { Add, Close, Filters } from '@hitachivantara/uikit-react-icons';
import { getTimeAndDate } from 'common/configs/utils';
import { useMemo, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { isNewWorkflow } from 'Redux/slices/workflowSlice/workflowSlice.selector';
import { CREATE_NEW, DEFAULT_WORKFLOW } from 'shared/constants/constants';

import { setWorkflowById } from '../../../Redux/slices/bpmnSlice/bpmnSlice';
import { setNewWorkflow } from '../../../Redux/slices/workflowSlice/workflowSlice';
import './WorkflowList.css';

// import { AssetEvent, getColumns, makeData } from "../storiesUtils";

const slide = keyframes`
  0% { 
    max-height: 0;
  }
  100% { 
    max-height: 300px;
  }
`;

const classes = {
  filtersContainer: css({
    display: 'flex',
    width: '100%',
    backgroundColor: theme.colors.warning_20,
    border: '2px solid black',
    overflow: 'hidden',
    animation: `${slide} 1.5s ease-in-out`,
  }),
  filters: css({
    display: 'flex',
    width: '100%',
    padding: theme.space.xs,
    justifyContent: 'space-between',
    alignItems: 'center',
  }),
  gemsContainer: css({
    display: 'flex',
    width: '100%',
    justifyContent: 'flex-start',
    padding: `0px ${theme.space.xs}`,
    flexWrap: 'wrap',
    gap: theme.space.xs,
  }),
  blank_row: css({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  filterHeader: css({
    borderColor: 'transparent',
    '&:hover': {
      borderColor: 'transparent',
      backgroundColor: theme.colors.primary_20,
    },
    '&:focus-visible': {
      borderColor: 'transparent',
    },
    [`&.${baseDropdownClasses.headerOpen}`]: {
      borderColor: theme.colors.secondary,
      '&:hover': {
        borderColor: theme.colors.secondary,
      },
    },
  }),
};

const filters: HvFilterGroupProps['filters'] = [
  {
    id: 'published',
    name: 'Published',
    data: [
      { id: 'true', name: 'yes' },
      { id: 'false', name: 'No' },
    ],
  },
];

function EmptyRow() {
  return (
    <HvTableRow>
      <HvTableCell colSpan={100} />
    </HvTableRow>
  );
}
function MakeData(initialState: Workflow[]) {
  const data = initialState.map((item) => {
    return {
      ...item,
      published: item.published ? 'Yes' : 'No',
      lastModified: getTimeAndDate(item.lastModified),
    };
  });
  return data;
}

function getColumns() {
  return [
    { Header: 'ID', accessor: 'id' },
    { Header: 'Name', accessor: 'name' },
    { Header: 'Description', accessor: 'description', disableSortBy: true },
    { Header: 'Last modified', accessor: 'lastModified' },
    { Header: 'Published', accessor: 'published', disableSortBy: true },
  ];
}

interface Workflow {
  id: number;
  name: string;
  description: string;
  published: boolean;
  lastModified: string;
  path: string;
}
interface TableProps {
  handleRowClick: (id: number) => void;
  workflowData: Workflow[];
}

function WorkflowList({ workflowData, handleRowClick }: TableProps) {
  const filterRef = useRef<HTMLDivElement>(null);
  const [data] = useState(MakeData(workflowData));
  console.log(data, 'data');
  const [selectedFilters, setSelectedFilters] = useState<HvFilterGroupValue>();
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const isNewWrkflwValue = useSelector(isNewWorkflow);

  const columns: HvTableColumnConfig[] = useMemo(() => {
    const cols = getColumns();

    return cols;
  }, []);

  const handleOnClick = () => {
    dispatch(
      setWorkflowById({
        name: '',
        description: '',
        id: 0,
        published: false,
        fileObject: DEFAULT_WORKFLOW,
      }),
    );
    dispatch(setNewWorkflow(!isNewWrkflwValue));
    navigate('/author/workflow');
  };

  const processedFilters = useMemo(
    () =>
      selectedFilters?.flatMap((categoryArray, idx) =>
        categoryArray?.map((value) => ({
          category: {
            label: filters[idx].name,
            id: filters[idx].id,
          },
          value: {
            label: filters[idx].data.find((x) => x.id === value)?.name,
            id: value,
          },
        })),
      ),
    [selectedFilters],
  );

  const {
    getTableProps,
    getTableBodyProps,
    prepareRow,
    headerGroups,
    page,
    getHvPaginationProps,
    state: { pageSize },
    setAllFilters,
    setGlobalFilter,
  } = useHvData(
    { columns, data },
    useHvFilters,
    useHvGlobalFilter,
    useHvSortBy,
    useHvPagination,
  );

  const renderTableRow = (i: number) => {
    const row = page[i];
    prepareRow(row);
    return (
      <HvTableRow
        {...row.getRowProps()}
        onClick={() => handleRowClick(row.original.id as number)}
      >
        {row.cells.map((cell) => {
          return (
            <HvTableCell {...cell.getCellProps()}>{cell.render('Cell')}</HvTableCell>
          );
        })}
      </HvTableRow>
    );
  };

  const handleFilters = (arrays?: HvFilterGroupValue) => {
    setSelectedFilters(arrays);
    const newFilters =
      arrays
        ?.map((array, idx) => ({
          id: filters[idx].id,
          value: array
            .map((x) => filters[idx].data.find((i) => i.id === x)?.name)
            .filter((v) => v),
        }))
        .flat() || [];
    setAllFilters?.(newFilters);
  };

  return (
    <div className="HvTableSection">
      <div className="box">
        <p className="workflows"> Workflows </p>
      </div>
      <HvTableSection
        raisedHeader
        title={<HvTypography variant="title4">Workflow Details</HvTypography>}
        actions={
          <>
            <HvInput
              type="search"
              placeholder="Search all columns"
              onChange={(_e, v) => setGlobalFilter?.(v)}
            />
            <HvFilterGroup
              ref={filterRef}
              filters={filters}
              disablePortal={false}
              value={selectedFilters}
              onChange={(_event, value) => handleFilters(value)}
              aria-label="Filters"
              filterContentProps={{
                adornment: <Filters aria-hidden />,
                placeholder: null,
                classes: {
                  header: classes.filterHeader,
                },
              }}
            />

            <HvButton
              className="create_button"
              variant="primaryGhost"
              startIcon={<Add />}
              type="submit"
              form="create-post"
              onClick={handleOnClick}
            >
              {CREATE_NEW}
            </HvButton>
          </>
        }
      >
        {processedFilters && processedFilters.length > 0 && (
          <div className={classes.filtersContainer}>
            <div className={classes.filters}>
              <HvButton
                variant="primaryGhost"
                startIcon={<Add />}
                onClick={() => filterRef.current?.click()}
              >
                Add Filter
              </HvButton>
              <div className={classes.gemsContainer}>
                {processedFilters.map(({ category, value }) => (
                  <HvButton
                    key={`gem-${category.id}-${value.id}`}
                    startIcon={<Close />}
                    variant="secondarySubtle"
                    onClick={() => {
                      const newFilters = selectedFilters?.map((array, idx) =>
                        idx === filters.findIndex((x) => x.id === category.id)
                          ? array.filter((x) => x !== value.id)
                          : array,
                      );
                      handleFilters(newFilters);
                    }}
                    aria-label={`Clear filter ${category.label}: ${value.label}`}
                  >
                    {category.label}: {value.label}
                  </HvButton>
                ))}
              </div>
              <HvButton variant="secondaryGhost" onClick={() => handleFilters(undefined)}>
                Clear
              </HvButton>
            </div>
          </div>
        )}
        <HvTableContainer className="HvTableContainer">
          <HvTable {...getTableProps()}>
            <HvTableHead>
              {headerGroups.map((headerGroup) => (
                <HvTableRow {...headerGroup.getHeaderGroupProps()}>
                  {headerGroup.headers.map((col) => {
                    let sortIndicator = '';
                    if (col.isSorted) {
                      if (col.isSortedDesc) {
                        sortIndicator = '';
                      } else {
                        sortIndicator = '';
                      }
                    }
                    return (
                      <HvTableHeader {...col.getHeaderProps()}>
                        {col.render('Header')}
                        {sortIndicator}
                      </HvTableHeader>
                    );
                  })}
                </HvTableRow>
              ))}
            </HvTableHead>
            <HvTableBody {...getTableBodyProps()}>
              {data.length === 0 ? (
                <EmptyRow />
              ) : (
                [...Array(pageSize ?? 0).keys()].map(renderTableRow)
              )}
            </HvTableBody>
          </HvTable>
        </HvTableContainer>
        {page.length > 0 ? (
          <HvPagination
            {...getHvPaginationProps?.()}
            labels={{
              pageSizePrev: '',
              pageSizeEntryName: `of ${data.length}`,
            }}
          />
        ) : undefined}
      </HvTableSection>
    </div>
  );
}

export default WorkflowList;

**Comment by Srikant1290** [comment] 2024-04-23 16:40
![Uploading image (5).png…]()

**Comment by Srikant1290** [comment] 2024-04-23 16:45
![image (6)](https://github.com/lumada-design/hv-uikit-react/assets/109790097/3d225efa-756c-4cbb-ae47-4a9f1b6ecedb)

**Comment by Srikant1290** [comment] 2024-04-23 16:46
![image (5)](https://github.com/lumada-design/hv-uikit-react/assets/109790097/1b518eeb-fc0c-4cf1-aff7-4d2e02c9fa52)

**Comment by MEsteves22** [comment] 2024-04-30 15:27
Hello @Srikant1290 👋 Do you still have this issue?

**Comment by Srikant1290** [comment] 2024-04-30 15:30
Yes, Still the issue is there

**Comment by MEsteves22** [comment] 2024-04-30 16:24
@Srikant1290 You can create an example with our [Stackblitz template](https://stackblitz.com/github/lumada-design/hv-uikit-react/tree/master/examples/uikit-vite-ts), please? At the moment we are unable to reproduce the issue on our end.

**Comment by MEsteves22** [comment] 2024-05-02 09:44
Hey 👋 Since this is the same issue as [this one](https://github.com/lumada-design/hv-uikit-react/issues/4165), we'll close this one and continue this thread on the other issue.

**Closed by MEsteves22** 2024-05-02 09:44 UTC
Labels: :mailbox_with_mail: waiting feedback
